/**
 * This package provides support for temporarily blocking construction in discrete cuboid regions.
 * The primary use case for this mechanism is to prevent players from editing temporary, non-natural structures,
 * which have been generated by plugins. For example, a hot air balloon which fell from the sky and will
 * disappear naturally in a few minutes, but not before sitting on the ground for a few moments. During these
 * moments players should not be allowed to delete the balloon.
 *
 * Plugins can hook into this mechanism by injecting {@link com.duncpro.bukkit.region.lock.PluginExtentLockFactory}.
 * A block may only be locked by a single plugin at a time. All locks are cooperative, as to never block
 * the main thread and lag the server. None of the classes in this package are thread safe, and should therefore
 * never be usde off of the main thread./
 */
package com.duncpro.bukkit.region.lock;
